# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='intro',
            field=models.TextField(),
        ),
    ]
