# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20171009_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='heading',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subheading',
            field=models.CharField(max_length=255),
        ),
    ]
